# Generated by Django 3.2.12 on 2024-01-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240119_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title')},
        ),
    ]
