# Generated by Django 3.2.12 on 2024-01-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_authorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='authorimage',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.author'),
        ),
    ]
