# Generated by Django 3.2.12 on 2024-01-28 10:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20240126_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.book')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ocijena mora biti najmanje 1.'), django.core.validators.MaxValueValidator(10, message='Ocijena mora biti najviše 10.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthorImage',
        ),
    ]
