# Generated by Django 3.2.12 on 2024-01-28 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Najmanja ocijena je 1.'), django.core.validators.MaxValueValidator(10, message='Najveća ocijena je 10.')]),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'surname')},
        ),
    ]
